-- 20251130140500_lessons_rls_teachers_read_authenticated.sql
-- Historical RLS change for "teachers read own lessons".
-- This policy no longer exists in the baseline schema and its logic
-- is already baked into 20250101000000_baseline_schema.sql.
-- Intentionally left as a no-op so the migration can be applied safely.
